# Generated by Django 4.2.21 on 2025-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
